services:
  - type: web
    name: chinese-dictation
    env: python
    buildCommand: : |
      pip install -r requirements.txt
      python init_db.py  # This creates progress.db
    startCommand: "python init_db.py && gunicorn 'run:create_app()'"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DB_PATH
        value: progress.db

